name: DogofDoom
favicon: null
layout_spectrum: 0.30186836887151003
typography_spectrum: 0.918162279529497
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#101813'
    - '#302d1f'
    - '#ded0bb'
    - '#b3a487'
    - '#545849'
  brandStrength: 0.25
  lightness: 0.3592752201948315
  saturation: 0.945020642131567
  rhythmicContrast: 0.9810869325883687
purpose: []
